name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install npm dependencies
        run: npm install

  package:
    needs: setup-environment
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.RELEASE_KEY }}
    steps:
      - name: Run package script
        run: npm run package

  typescript-compile:
    needs: setup-environment
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.RELEASE_KEY }}
    steps:
      - name: Compile TypeScript
        run: npm exec tsc

  test:
    needs: setup-environment
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.RELEASE_KEY }}
    steps:
      - name: Run tests
        run: npm test
