name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  git-checkout:
    runs-on: windows-latest
    uses: actions/checkout@v3

  install-node:
    needs: git-checkout

    runs-on: windows-latest
    uses: actions/setup-node@v3
    with:
      node-version: 18
      cache: npm

  npm-install:
    needs: install-node

    runs-on: windows-latest
    run: |
      npm install

  package:
    needs: npm-install

    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.RELEASE_KEY }}
    run: |
      npm run package

  typescript-compile:
    needs: npm-install

    runs-on: windows-latest
    env:
        GH_TOKEN: ${{ secrets.RELEASE_KEY }}
      run: |
        npm exec tsc

  test:
    needs: npm-install

    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.RELEASE_KEY }}
    run: |
      npm test
