name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: Increment minor version
        run: npm version minor -m "v%s"

      - name: Get new version
        id: get_version
        run: echo VERSION=$(node -p "require('./package.json').version")

      - name: Create and push new tag
        env:
          VERSION: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_KEY }}
        run: |
          git tag $VERSION
          git push origin --follow-tags
          git push origin $VERSION
