name: Version

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Increment Minor version number
        env:
          GH_TOKEN: ${{ secrets.RELEASE_KEY }}
        run: |
          git stash
          npm version minor -m "[ci skip]"
          git stash pop
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
